services:
  ms1-usuarios:
    image: pauloimb/ms1-usuarios:latest
    container_name: ms1-usuarios
    restart: unless-stopped
    ports:
      - "8001:8000"
    networks:
      - backend
    # environment:
    #   NODE_ENV: production
    #   PORT: 3001

  ms2-productos:
    image: vssz01/ms2_productos:latest
    container_name: ms2-productos
    restart: unless-stopped
    ports:
      - "8002:8080"
    networks:
      - backend
    environment:
      DB_HOST: 18.215.44.221
      DB_PORT: 5555
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: 123
      CORS_ALLOWED_ORIGINS: "*"

  ms3-pedidos:
    image: jc01010101/ms3-pedidos:v1
    container_name: ms3-pedidos
    restart: unless-stopped
    ports:
      - "8003:3003"
    networks:
      - backend
    environment:
    #   NODE_ENV: production
      MONGO_URI: mongodb://admin:admin@18.215.44.221:27017/ms3?authSource=admin
      MS1_USUARIOS_API_URL: http://ms1-usuarios:8000
      MS2_PRODUCTOS_API_URL: http://ms2-productos:8080
      PORT: 3003
      CORS_ORIGIN: "*"
      
networks:
  backend:
    driver: bridge

